### ISSUE TITLE
Remove USB/Device 

### ISSUE THREAD

**Issue by DrJeff** [codekitchen/alarmdecoder-webapp-dockerfile#1]
Any way to remove the need for USB so this can be run in a docker with Socket connection?
Thanks,
Jeff

**Comment by codekitchen** [comment]
I've never tried running AlarmDecoder over a socket connection, but it shouldn't take any changes to this Dockerfile -- just omit the `--device=<device_id>` argument when launching the container, or the equivalent `device:` line in the compose file.

**Comment by DrJeff** [comment]
Hey Brian I tried that but ever gas and log cannot chmod the USB. Even when
I take out the chmod from the start.sh file same thing. Anything else?
Maybe some ideas?
Jeff

**Comment by codekitchen** [comment]
Oh I'd forgotten about that start.sh line. I've just published a new version of the image with [this commit](https://github.com/codekitchen/alarmdecoder-webapp-dockerfile/commit/b4d5137cae5ebf9f3162847749fb3a9f7ac4953d) which will allow start.sh to succeed even if there's no USB device.

**Comment by DrJeff** [comment]
Awesomeness!
That did the trick now got my AD2USB on a ser2sock serving to Home Assistant, XTension on a mac, and terminal all simultaneously.
Thanks! 😃
